/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class textmatch_ScreenshotTaker */

#ifndef _Included_textmatch_ScreenshotTaker
#define _Included_textmatch_ScreenshotTaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     textmatch_ScreenshotTaker
 * Method:    initializeXInteraction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_textmatch_ScreenshotTaker_initializeXInteraction
  (JNIEnv *, jclass);

/*
 * Class:     textmatch_ScreenshotTaker
 * Method:    refreshInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_textmatch_ScreenshotTaker_refreshInfo
  (JNIEnv *, jclass);

/*
 * Class:     textmatch_ScreenshotTaker
 * Method:    getX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_textmatch_ScreenshotTaker_getX
  (JNIEnv *, jclass);

/*
 * Class:     textmatch_ScreenshotTaker
 * Method:    getY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_textmatch_ScreenshotTaker_getY
  (JNIEnv *, jclass);

/*
 * Class:     textmatch_ScreenshotTaker
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_textmatch_ScreenshotTaker_getWidth
  (JNIEnv *, jclass);

/*
 * Class:     textmatch_ScreenshotTaker
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_textmatch_ScreenshotTaker_getHeight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
